# Generated by Django 2.1.5 on 2019-01-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('DOB', models.DateTimeField(verbose_name='DOB')),
                ('current_city_or_county', models.CharField(max_length=50)),
                ('current_state', models.CharField(max_length=2)),
                ('current_zip', models.CharField(max_length=9)),
                ('current_country', models.CharField(max_length=15)),
                ('veteran_status', models.BooleanField()),
                ('hcv_recipient', models.BooleanField()),
                ('VASH', models.BooleanField()),
                ('other_subsidy', models.BooleanField()),
                ('differently_abled', models.BooleanField()),
                ('hearing_impaired', models.BooleanField()),
                ('deaf', models.BooleanField()),
                ('visually_impaired', models.BooleanField()),
                ('blind', models.BooleanField()),
                ('physically_impaired', models.BooleanField()),
                ('wheelchair', models.BooleanField()),
                ('walker', models.BooleanField()),
                ('intellectually_impaired', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('landlord_address1', models.CharField(max_length=200)),
                ('landlord_address2', models.CharField(max_length=200)),
                ('landlord_state', models.CharField(max_length=2)),
                ('landlord_zip', models.CharField(max_length=9)),
                ('website', models.CharField(max_length=200)),
                ('nonprofit_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_address1', models.CharField(max_length=200)),
                ('property_address2', models.CharField(max_length=200)),
                ('property_state', models.CharField(max_length=2)),
                ('property_zip', models.CharField(max_length=9)),
                ('property_email', models.CharField(max_length=15)),
                ('property_phone', models.CharField(max_length=15)),
                ('year_built', models.DateTimeField(verbose_name='YearBuilt')),
                ('website', models.CharField(max_length=200)),
                ('nonprofit_flag', models.BooleanField()),
                ('has_accessible_unit', models.BooleanField()),
                ('full_waitlist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Applicant')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Property')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Property'),
        ),
    ]
