# Generated by Django 2.1.5 on 2019-01-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.CharField(max_length=15),
        ),
    ]
